[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.8", features = ["android-native-activity"] }
wgpu = "27.0.1"
env_logger = "0.11.8"
pollster = "0.4.0"





